{ Parsed from IOKit.framework IOHIDProperties.h }

{$ifndef IOHIDProperties_h}
{$ifdef TYPES}
const
  kIOHIDPointerAccelerationKey = 'HIDPointerAcceleration';
  kIOHIDPointerAccelerationTypeKey = 'HIDPointerAccelerationType';
  kIOHIDMouseScrollAccelerationKey = 'HIDMouseScrollAcceleration';
  kIOHIDMouseAccelerationType = 'HIDMouseAcceleration';
  kIOHIDMouseAccelerationTypeKey = kIOHIDMouseAccelerationType;
  kIOHIDScrollAccelerationKey = 'HIDScrollAcceleration';
  kIOHIDScrollAccelerationTypeKey = 'HIDScrollAccelerationType';
  kIOHIDPointerButtonMode = 'HIDPointerButtonMode';
  kIOHIDPointerButtonModeKey = kIOHIDPointerButtonMode;
  kIOHIDUserUsageMapKey = 'UserKeyMapping';
  kIOHIDKeyboardCapsLockDelayOverride = 'CapsLockDelayOverride';
  kIOHIDKeyboardCapsLockDelayOverrideKey = kIOHIDKeyboardCapsLockDelayOverride;
  kIOHIDServiceEjectDelayKey = 'EjectDelay';
  kIOHIDServiceInitialKeyRepeatDelayKey = 'HIDInitialKeyRepeat';
  kIOHIDServiceKeyRepeatDelayKey = 'HIDKeyRepeat';
{$endif}

{$endif}
